<h1>Aravinth R - 19MIC0053
<br>
NLTK Session

<h1>Part I

In [ ]:
pip install nltk

In [ ]:
import nltk

In [ ]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipp

True

In [ ]:
#Brown

from nltk.corpus import brown

In [ ]:
brown.words(categories='romance')[:50]

['They',
 'neither',
 'liked',
 'nor',
 'disliked',
 'the',
 'Old',
 'Man',
 '.',
 'To',
 'them',
 'he',
 'could',
 'have',
 'been',
 'the',
 'broken',
 'bell',
 'in',
 'the',
 'church',
 'tower',
 'which',
 'rang',
 'before',
 'and',
 'after',
 'Mass',
 ',',
 'and',
 'at',
 'noon',
 ',',
 'and',
 'at',
 'six',
 'each',
 'evening',
 '--',
 'its',
 'tone',
 ',',
 'repetitive',
 ',',
 'monotonous',
 ',',
 'never',
 'breaking',
 'the',
 'boredom']

In [ ]:
from nltk.corpus import inaugural 
inaugural.fileids()
inaugural.words(fileids= '1801-Jefferson.txt')[:50]


['Friends',
 'and',
 'Fellow',
 'Citizens',
 ':',
 'Called',
 'upon',
 'to',
 'undertake',
 'the',
 'duties',
 'of',
 'the',
 'first',
 'executive',
 'office',
 'of',
 'our',
 'country',
 ',',
 'I',
 'avail',
 'myself',
 'of',
 'the',
 'presence',
 'of',
 'that',
 'portion',
 'of',
 'my',
 'fellow',
 'citizens',
 'which',
 'is',
 'here',
 'assembled',
 'to',
 'express',
 'my',
 'grateful',
 'thanks',
 'for',
 'the',
 'favor',
 'with',
 'which',
 'they',
 'have',
 'been']

In [ ]:
text1='Peter Pan is a 1953 American animated adventure fantasy film produced by Walt Disney Productions and based on the 1904 play Peter Pan, or The Boy Who Wouldnt Grow Up by J. M. Barrie. Directed by Clyde Geronimi, Hamilton Luske and Wilfred Jackson, it is the 14th Disney animated feature film. Starring the voices of Bobby Driscoll, Kathryn Beaumont, Hans Conried, Paul Collins, Heather Angel, and Bill Thompson, the films plot involves a group of kids who meet Peter Pan and travel to the island of Never Land to stay young, where Peter also attempts to evade Captain Hook.'
fd=nltk.FreqDist(text1.split())
fd

FreqDist({'14th': 1,
          '1904': 1,
          '1953': 1,
          'American': 1,
          'Angel,': 1,
          'Barrie.': 1,
          'Beaumont,': 1,
          'Bill': 1,
          'Bobby': 1,
          'Boy': 1,
          'Captain': 1,
          'Clyde': 1,
          'Collins,': 1,
          'Conried,': 1,
          'Directed': 1,
          'Disney': 2,
          'Driscoll,': 1,
          'Geronimi,': 1,
          'Grow': 1,
          'Hamilton': 1,
          'Hans': 1,
          'Heather': 1,
          'Hook.': 1,
          'J.': 1,
          'Jackson,': 1,
          'Kathryn': 1,
          'Land': 1,
          'Luske': 1,
          'M.': 1,
          'Never': 1,
          'Pan': 2,
          'Pan,': 1,
          'Paul': 1,
          'Peter': 4,
          'Productions': 1,
          'Starring': 1,
          'The': 1,
          'Thompson,': 1,
          'Up': 1,
          'Walt': 1,
          'Who': 1,
          'Wilfred': 1,
          'Wouldnt': 1,
          'a': 2,
      

In [ ]:
from nltk.probability import ConditionalFreqDist
cfd= ConditionalFreqDist((len(word),word) for word in text1.split())
cfd[6]

FreqDist({'Angel,': 1,
          'Disney': 2,
          'island': 1,
          'travel': 1,
          'voices': 1,
          'young,': 1})

<h1>Part II

In [ ]:
#Task 1
#Lexicon - Stop Words

In [ ]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [ ]:
#Task 2
#CMUdict - Pronunciation Info

In [ ]:
entries= nltk.corpus.cmudict.entries()
len(entries)
entries[:15]

[('a', ['AH0']),
 ('a.', ['EY1']),
 ('a', ['EY1']),
 ('a42128',
  ['EY1',
   'F',
   'AO1',
   'R',
   'T',
   'UW1',
   'W',
   'AH1',
   'N',
   'T',
   'UW1',
   'EY1',
   'T']),
 ('aaa', ['T', 'R', 'IH2', 'P', 'AH0', 'L', 'EY1']),
 ('aaberg', ['AA1', 'B', 'ER0', 'G']),
 ('aachen', ['AA1', 'K', 'AH0', 'N']),
 ('aachener', ['AA1', 'K', 'AH0', 'N', 'ER0']),
 ('aaker', ['AA1', 'K', 'ER0']),
 ('aalseth', ['AA1', 'L', 'S', 'EH0', 'TH']),
 ('aamodt', ['AA1', 'M', 'AH0', 'T']),
 ('aancor', ['AA1', 'N', 'K', 'AO2', 'R']),
 ('aardema', ['AA0', 'R', 'D', 'EH1', 'M', 'AH0']),
 ('aardvark', ['AA1', 'R', 'D', 'V', 'AA2', 'R', 'K']),
 ('aaron', ['EH1', 'R', 'AH0', 'N'])]

In [ ]:
#Task 3

In [ ]:
from nltk.corpus import wordnet as wn
wn.synsets('Aeroplane')

[Synset('airplane.n.01')]

In [ ]:
wn.synset('airplane.n.01').lemma_names()

['airplane', 'aeroplane', 'plane']

In [ ]:
from nltk.corpus import names

def gender_features(word):
  return{'last_letter':word[-1]}

In [ ]:
gender_features('Donald')

{'last_letter': 'd'}

In [ ]:
labeled_names=([(name,'male') for name in names.words('male.txt')]+[(name,'female') for name in names.words('female.txt')])

In [ ]:
import random
random.shuffle(labeled_names)

In [ ]:
featuresets=[(gender_features(n),gender) for (n,gender) in labeled_names]

In [ ]:
train_set,test_set=featuresets[500:],featuresets[:500]

In [ ]:
classifier=nltk.NaiveBayesClassifier.train(train_set)

In [ ]:
classifier.classify(gender_features('Donald'))

'male'

In [ ]:
classifier.classify(gender_features('Pranauv'))

'male'

In [ ]:
#Task 5 - Stemming

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
stemmerporter=PorterStemmer()
stemmerporter.stem('Successfully')

'success'

In [ ]:
from nltk.stem import LancasterStemmer

In [ ]:
stemmerlancaster=LancasterStemmer()
stemmerlancaster.stem('Impossible')

'imposs'

In [ ]:
from nltk.stem import RegexpStemmer

In [ ]:
stemmer=RegexpStemmer('Un')
stemmer.stem('Unresponsive')


'responsive'

In [ ]:
stemmer=RegexpStemmer('ing')
stemmer.stem('Doing')

'Do'

In [ ]:
from nltk.stem import SnowballStemmer

In [ ]:
french=SnowballStemmer('french')
french.stem('manges')

'mang'

In [ ]:
example='She is having fun reading the book on writing'
example=[stemmerporter.stem(token) for token in example.split(" ")]
print(" ".join(example))

she is have fun read the book on write


# Part III

### 24/11/2021

In [ ]:
#Task 1

In [ ]:
from nltk.stem import WordNetLemmatizer
lm=WordNetLemmatizer()
print(lm.lemmatize("formulae"))

formula


In [ ]:
print(lm.lemmatize("women"))

woman


In [ ]:
print(lm.lemmatize("better",pos='a'))

good


In [ ]:
print(lm.lemmatize("am",pos='v'))

be


In [ ]:
pip install jieba

In [ ]:
import jieba

In [ ]:
#Chinese Segmentation

In [ ]:
seg=jieba.cut("美國東南部的佛罗里达州拥有282个城市，109个鎮和19个村，共计410个注册成立的市法团。这些市法团分布在全州的67个县，共有66个县政府。杰克逊维尔拥有全州唯一一个市县合一的地方政府，所以杜瓦尔县没有县政府。不过，一些合并的市法团中可能还会有较小的市级政府，例如鲍德温和杰克逊维尔海滩群。全州所有的县城中只有一个不是注册成立的市法团，这个例外就是沃库拉县县城克劳福德维尔")
print(" ".join (seg))

Building prefix dict from the default dictionary ...
Dumping model to file cache /tmp/jieba.cache
Loading model cost 1.061 seconds.
Prefix dict has been built successfully.


美國東 南部 的 佛罗里达州 拥有 282 个 城市 ， 109 个鎮 和 19 个村 ， 共计 410 个 注册 成立 的 市法团 。 这些 市法团 分布 在 全州 的 67 个 县 ， 共有 66 个 县政府 。 杰克逊 维尔 拥有 全州 唯一 一个 市县 合一 的 地方 政府 ， 所以 杜瓦尔 县 没有 县政府 。 不过 ， 一些 合并 的 市法团 中 可能 还会 有 较 小 的 市级 政府 ， 例如 鲍德温 和 杰克逊 维尔 海滩 群 。 全州 所有 的 县城 中 只有 一个 不是 注册 成立 的 市法团 ， 这个 例外 就是 沃库 拉县 县城 克劳福德 维尔


In [ ]:
sent="you are an expert in NLTK now!"
words=nltk.word_tokenize(sent)
words

['you', 'are', 'an', 'expert', 'in', 'NLTK', 'now', '!']

In [ ]:
texts=""" Jai Bhim (alternatively spelled Jay Bhim or Jai Bheem; transl. "Victory for Bhim", "Long live Bhim" or "Hail Bhim") is a slogan and greeting used by followers of Bhimrao Ramji Ambedkar, an Indian scholar, social reformer and the chief architect of the Constitution of India. Jai Bhim literally means "Victory to Bhim" referring to B. R. Ambedkar.[1][2] In 1935, Jai Bhim conceived and developed by Babu L. N. Hardas (1904 – 1939),[3][4] a staunch follower of Babasaheb Ambedkar, and the secretary of Samata Sainik Dal.[5][6] However, its origin is obscure and may date as far back as 1818, well before Ambedkar's birth. """

In [ ]:
for text in texts:
  sentences=nltk.sent_tokenize(texts)
  for sentence in sentences:
    words=nltk.word_tokenize(sentence)
    tagged=nltk.pos_tag(words)
    print(tagged)

[('Jai', 'NNP'), ('Bhim', 'NNP'), ('(', '('), ('alternatively', 'RB'), ('spelled', 'VBN'), ('Jay', 'NNP'), ('Bhim', 'NNP'), ('or', 'CC'), ('Jai', 'NNP'), ('Bheem', 'NNP'), (';', ':'), ('transl', 'NN'), ('.', '.')]
[('``', '``'), ('Victory', 'NN'), ('for', 'IN'), ('Bhim', 'NNP'), ("''", "''"), (',', ','), ('``', '``'), ('Long', 'RB'), ('live', 'JJ'), ('Bhim', 'NNP'), ("''", "''"), ('or', 'CC'), ('``', '``'), ('Hail', 'NNP'), ('Bhim', 'NNP'), ("''", "''"), (')', ')'), ('is', 'VBZ'), ('a', 'DT'), ('slogan', 'JJ'), ('and', 'CC'), ('greeting', 'VBG'), ('used', 'VBN'), ('by', 'IN'), ('followers', 'NNS'), ('of', 'IN'), ('Bhimrao', 'NNP'), ('Ramji', 'NNP'), ('Ambedkar', 'NNP'), (',', ','), ('an', 'DT'), ('Indian', 'JJ'), ('scholar', 'NN'), (',', ','), ('social', 'JJ'), ('reformer', 'NN'), ('and', 'CC'), ('the', 'DT'), ('chief', 'JJ'), ('architect', 'NN'), ('of', 'IN'), ('the', 'DT'), ('Constitution', 'NNP'), ('of', 'IN'), ('India', 'NNP'), ('.', '.')]
[('Jai', 'NNP'), ('Bhim', 'NNP'), ('litera

# Open CV Session


In [ ]:
pip install opencv-contrib-python

In [ ]:
import cv2
from skimage import io

In [ ]:
import numpy 

In [ ]:
img=numpy.zeros((3,3),dtype=numpy.uint8)

In [ ]:
print(img)
print(img.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)


In [ ]:
img1=cv2.cvtColor(img,cv2.COLOR_GRAY2BGR)
print(img1)
print(img1.shape)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
(3, 3, 3)


In [ ]:
image=io.imread("https://tinyjpg.com/images/social/website.jpg")
print(image.shape)

(510, 1020, 3)


In [ ]:
cv2.imwrite("website.PNG",image)
print(image)
print(image.shape)

[[[158 182 194]
  [164 187 201]
  [166 190 202]
  ...
  [ 48  71  27]
  [143 165 152]
  [163 184 189]]

 [[159 183 193]
  [162 185 199]
  [165 188 202]
  ...
  [ 21  42   9]
  [110 131 126]
  [161 180 194]]

 [[161 186 193]
  [159 182 196]
  [162 185 203]
  ...
  [ 17  36  14]
  [ 85 105 103]
  [166 185 199]]

 ...

 [[107 135  16]
  [ 93 115   7]
  [ 93 114   0]
  ...
  [114 139   9]
  [130 153   0]
  [138 160   0]]

 [[100 127  10]
  [ 89 109  10]
  [ 86 104   0]
  ...
  [114 137   7]
  [126 146   0]
  [131 152   0]]

 [[ 88 115   0]
  [ 86 103   9]
  [ 79  96   0]
  ...
  [114 135   4]
  [121 140   0]
  [123 146   0]]]
(510, 1020, 3)


In [ ]:
import os

In [ ]:
randomByteArray=bytearray(os.urandom(120000))
flatnumpyarray=numpy.array(randomByteArray)

In [ ]:
bgrImage=flatnumpyarray.reshape(100,400,3)

In [ ]:
cv2.imwrite('randombgr.png',bgrImage)

True